FROM node

# Set working directory
RUN mkdir -p /app
WORKDIR /app

# add `/usr/src/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH
# create user with no password
RUN adduser --disabled-password tinder

# Copy existing application directory contents
COPY . /app
# install and cache app dependencies
COPY package.json /app/package.json
COPY package-lock.json /app/package-lock.json

# grant a permission to the application
RUN chown -R tinder:tinder /app
USER tinder

# clear application caching
RUN npm cache clean --force
# install all dependencies
RUN npm install

EXPOSE 4000
CMD [ "npm", "run", "start:dev" ]